#!/bin/sh

# Check frontend changes
if git diff --cached --name-only | grep -q "^frontend/"; then
  echo "Running frontend checks..."
  cd frontend && npx lint-staged
  if [ $? -ne 0 ]; then
    echo "Frontend pre-commit checks failed"
    exit 1
  fi
  cd ..
fi

# Check backend changes
if git diff --cached --name-only | grep -q "^backend/"; then
  # Store list of staged kotlin files
  STAGED_FILES=$(git diff --cached --name-only | grep "^backend/.*\.kt$")
  
  echo "Running backend checks..."
  cd backend && ./gradlew detektTwice
  if [ $? -ne 0 ]; then
    echo "Backend pre-commit checks failed"
    exit 1
  fi
  cd ..
  
  # Re-stage only the files that were originally staged (to include formatting fixes)
  echo "$STAGED_FILES" | xargs -r git add
fi